SportStore.WebUI/Controllers/AdminController.cs
using SportStore.Domain.Abstract;
using SportStore.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IProductRepository repository;

        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }

        public ActionResult Index()
        {
            IEnumerable<Product> Products = repository.Products;
            return View(Products);
        }

        public ActionResult Edit(int id)
        {
            Product p = repository.Products
                .FirstOrDefault(s => s.ProductID == id);
            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(Product p)
        {
            if (ModelState.IsValid)
            {
                if (p.ProductID == 0)
                    repository.SaveProduct(p);
                else repository.UpdateProduct(p);

                TempData["message"] = string.Format("Pomyślnie zapisano {0}", p.Name);
                return RedirectToAction("Index");
            }
            else
                return View(p);
        }

        public ActionResult Delete(string name, int id)
        {
            repository.DeleteProduct(id);
            TempData["message"] = string.Format("Usunięto {0}", name);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View("Edit", new Product());
        }
    }
}

SportStore.WebUI/Controllers/ProductController.cs
using SportStore.Domain.Abstract;
using SportStore.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository; //to jest klasa EFProductRepository z listą produktów
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? 
                        repository.Products.Count() :
                        repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

SportStore.WebUI/Views/Admin/Edit.cshtml
@model SportStore.Domain.Entities.Product
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edycja</h2>

@using (Html.BeginForm("Edit", "Admin"))
{
    <div class="panel-body">
        @Html.HiddenFor(p => p.ProductID)

    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Name)
        @Html.TextBoxFor(p => p.Name, null, new { @class = "form-control"})
        @Html.ValidationMessageFor(p => p.Name, null, new { @class = "error" })
    </div>

    <div>
        @Html.LabelFor(p => p.Description)
        @Html.TextBoxFor(p => p.Description, null, new { @class = "form-control", rows = 5 })
        @Html.ValidationMessageFor(p => p.Description, null, new { @class = "error"})
    </div>

    <div>
        @Html.LabelFor(p => p.Category)
        @Html.TextBoxFor(p => p.Category, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Category, null, new { @class = "error" })
    </div>

    <div>
        @Html.LabelFor(p => p.Price)
        @Html.TextBoxFor(p => p.Price, null, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Price, null, new { @class = "error" })
    </div>
    <div class="panel-footer">
        <input type="submit" value="Zapisz" class="btn btn-primary" />
        @Html.ActionLink("Anuluj", "Index", null, new { @class = "btn btn-default" })
    </div>
}

SportStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportStore.Domain.Entities.Product>
@{
    ViewBag.Title = "Administracja: Wszystkie produkty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<dev>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
            <tr>
                <td>ID</td>
                <td>Nazwa</td>
                <td>Cena</td>
                <td>Akcje</td>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tbody>
                <tr class="form-group">
                    <td>@item.ProductID</td>
                    <td>@item.Name</td>
                    <td>@item.Price</td>
                    <td>
                        @Html.ActionLink("Edytuj", "Edit", "Admin", new { id = item.ProductID }, null)
                        @Html.ActionLink("Usuń", "Delete", "Admin", new { name = item.Name, id = item.ProductID }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            </tbody>
        }
    </table>
    @Html.ActionLink("Dodaj produkt", "Create", null, new { @class = "btn btn-default"})
    @Html.ActionLink("Powrót do strony głównej", "List", "Product", null, new { @class = "btn btn-default" })
</dev>
